"use client";
import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { useEffect } from "react";
import {supabase} from "@/lib/supabaseClient";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    

  
    useEffect(() => {
    const test = async () => {
      const { data } = await supabase.from("users").select("*")
      console.log("Usuarios:", data)
    }
    test()
  }, [])



  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
